// Common travel data for quick entry

export const AIRLINES = [
  'United Airlines',
  'American Airlines',
  'Delta Air Lines',
  'Southwest Airlines',
  'JetBlue Airways',
  'Alaska Airlines',
  'Spirit Airlines',
  'Frontier Airlines',
  'Air Canada',
  'British Airways',
  'Lufthansa',
  'Emirates',
  'Qatar Airways',
  'Singapore Airlines',
  'Cathay Pacific',
  'Air France',
  'KLM',
  'Turkish Airlines',
  'Etihad Airways',
  'Virgin Atlantic',
  'ANA (All Nippon Airways)',
  'Japan Airlines',
  'Korean Air',
  'Qantas',
  'Iberia',
  'Swiss International Air Lines',
  'Austrian Airlines',
  'Brussels Airlines',
  'Aer Lingus',
  'Norwegian Air',
  'WestJet',
  'Avianca',
  'LATAM Airlines',
  'Air China',
  'China Eastern Airlines',
  'China Southern Airlines',
  'IndiGo',
  'Air India',
  'Thai Airways',
  'Malaysia Airlines',
  'Philippine Airlines',
  'Vietnam Airlines',
  'Garuda Indonesia',
  'Air New Zealand',
  'South African Airways',
  'Ethiopian Airlines',
  'Kenya Airways',
  'EgyptAir',
  'El Al',
  'Saudi Arabian Airlines',
  'Gulf Air',
]

export const AIRPORTS = [
  // US Major Airports
  'ATL - Hartsfield-Jackson Atlanta',
  'LAX - Los Angeles International',
  'ORD - Chicago O\'Hare',
  'DFW - Dallas/Fort Worth',
  'DEN - Denver International',
  'JFK - John F. Kennedy (New York)',
  'SFO - San Francisco International',
  'SEA - Seattle-Tacoma',
  'LAS - Las Vegas McCarran',
  'MCO - Orlando International',
  'EWR - Newark Liberty',
  'CLT - Charlotte Douglas',
  'PHX - Phoenix Sky Harbor',
  'IAH - Houston George Bush',
  'MIA - Miami International',
  'BOS - Boston Logan',
  'MSP - Minneapolis-St. Paul',
  'FLL - Fort Lauderdale',
  'DTW - Detroit Metropolitan',
  'PHL - Philadelphia International',
  'LGA - LaGuardia (New York)',
  'BWI - Baltimore/Washington',
  'SLC - Salt Lake City',
  'IAD - Washington Dulles',
  'DCA - Reagan National (DC)',
  'MDW - Chicago Midway',
  'SAN - San Diego International',
  'TPA - Tampa International',
  'PDX - Portland International',
  'STL - St. Louis Lambert',
  
  // International Major Airports
  'LHR - London Heathrow',
  'CDG - Paris Charles de Gaulle',
  'FRA - Frankfurt',
  'AMS - Amsterdam Schiphol',
  'MAD - Madrid Barajas',
  'BCN - Barcelona El Prat',
  'FCO - Rome Fiumicino',
  'MXP - Milan Malpensa',
  'MUC - Munich',
  'ZRH - Zurich',
  'VIE - Vienna',
  'BRU - Brussels',
  'DUB - Dublin',
  'CPH - Copenhagen',
  'ARN - Stockholm Arlanda',
  'OSL - Oslo Gardermoen',
  'HEL - Helsinki Vantaa',
  'IST - Istanbul',
  'DXB - Dubai International',
  'DOH - Doha Hamad',
  'AUH - Abu Dhabi',
  'CAI - Cairo',
  'JNB - Johannesburg',
  'CPT - Cape Town',
  'NRT - Tokyo Narita',
  'HND - Tokyo Haneda',
  'KIX - Osaka Kansai',
  'ICN - Seoul Incheon',
  'PVG - Shanghai Pudong',
  'PEK - Beijing Capital',
  'HKG - Hong Kong',
  'SIN - Singapore Changi',
  'BKK - Bangkok Suvarnabhumi',
  'KUL - Kuala Lumpur',
  'CGK - Jakarta',
  'MNL - Manila',
  'SYD - Sydney',
  'MEL - Melbourne',
  'AKL - Auckland',
  'YYZ - Toronto Pearson',
  'YVR - Vancouver',
  'YUL - Montreal Trudeau',
  'MEX - Mexico City',
  'GRU - São Paulo Guarulhos',
  'GIG - Rio de Janeiro',
  'EZE - Buenos Aires Ezeiza',
  'SCL - Santiago',
  'BOG - Bogotá',
  'LIM - Lima',
]

export const TERMINALS = [
  'Terminal 1',
  'Terminal 2',
  'Terminal 3',
  'Terminal 4',
  'Terminal 5',
  'Terminal A',
  'Terminal B',
  'Terminal C',
  'Terminal D',
  'Terminal E',
  'Terminal F',
  'International Terminal',
  'Domestic Terminal',
  'North Terminal',
  'South Terminal',
  'East Terminal',
  'West Terminal',
  'Central Terminal',
  'Main Terminal',
]

export const TRANSPORT_TYPES = [
  'Taxi',
  'Uber',
  'Lyft',
  'Rental Car',
  'Train',
  'Subway/Metro',
  'Bus',
  'Shuttle',
  'Private Car',
  'Limousine',
  'Ferry',
  'Tram',
  'Hotel Shuttle',
  'Airport Shuttle',
]

export const HOTEL_CHAINS = [
  'Marriott',
  'Hilton',
  'Hyatt',
  'InterContinental (IHG)',
  'Four Seasons',
  'Ritz-Carlton',
  'Westin',
  'Sheraton',
  'W Hotels',
  'Waldorf Astoria',
  'St. Regis',
  'Fairmont',
  'Sofitel',
  'Radisson',
  'Best Western',
  'Holiday Inn',
  'Courtyard',
  'Hampton Inn',
  'Residence Inn',
  'DoubleTree',
  'Embassy Suites',
  'Crowne Plaza',
  'Novotel',
  'Ibis',
  'Accor',
  'Motel 6',
  'Super 8',
  'Days Inn',
  'La Quinta',
  'Comfort Inn',
  'Quality Inn',
  'Red Roof Inn',
  'Extended Stay America',
  'Homewood Suites',
  'Staybridge Suites',
  'Kimpton',
  'Aloft',
  'Element',
  'Moxy',
  'Ace Hotel',
  'citizenM',
  'YOTEL',
]
